// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5rfgMWYsszoLTXIsJS1rP1bXWPD1QBAg',
    appId: '1:147200367642:web:df42fac015fe4c0fdb05a3',
    messagingSenderId: '147200367642',
    projectId: 'flutterwcapp',
    authDomain: 'flutterwcapp.firebaseapp.com',
    storageBucket: 'flutterwcapp.firebasestorage.app',
    measurementId: 'G-57LZFW42P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYkaqoJrNx-IpqDUFwqe4zeEAkYWPRFjc',
    appId: '1:147200367642:android:339ba23fd8750c2ddb05a3',
    messagingSenderId: '147200367642',
    projectId: 'flutterwcapp',
    storageBucket: 'flutterwcapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl3CPHQnPjAM21Jqr3n3CfWgLjxh_tQBI',
    appId: '1:147200367642:ios:1549d2466f51145fdb05a3',
    messagingSenderId: '147200367642',
    projectId: 'flutterwcapp',
    storageBucket: 'flutterwcapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterWcApp',
  );
}
